import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import { getDataHome } from "@/utils/actions/get-data";
import { HomeProps } from "@/utils/home.type";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { object }: HomeProps = await getDataHome();

  return (
    <html lang="en">
      <body>
        <Header logo={object.metadata.logo.url} />
        {children}
      </body>
    </html>
  );
}
